// Generated by https://quicktype.io

export interface AutoMixPreviewRenderer {
	automixPreviewVideoRenderer: AutomixPreviewVideoRenderer;
}

export interface AutomixPreviewVideoRenderer {
	content: Content;
}

export interface Content {
	automixPlaylistVideoRenderer: AutomixPlaylistVideoRenderer;
}

export interface AutomixPlaylistVideoRenderer {
	navigationEndpoint: NavigationEndpoint;
	trackingParams: string;
}

export interface NavigationEndpoint {
	clickTrackingParams: string;
	watchPlaylistEndpoint: WatchPlaylistEndpoint;
}

export interface WatchPlaylistEndpoint {
	playlistId: string;
	params: string;
}
