// Generated by https://quicktype.io

export interface BeatbumpSchema {
	/**
	 * Deployment configuration
	 */
	environment?: Environment;
	/**
	 * Platform specific configuration
	 * This will get passed onto the adapter (if applicable)
	 */
	platform?: Platform;
	/**
	 * The port that SvelteKit should listen for requests on.
	 * This property is required for the Node adapter and is unused on others.
	 */
	port?: number;
}

/**
 * Deployment configuration
 */
export interface Environment {
	/**
	 * The adapter to use for production deployments (Node, Cloudflare Workers, Vercel, etc..)
	 */
	adapter?: string;
	/**
	 * Proxy requests for songs if client is region-restricted (NOT IMPLEMENTED)
	 */
	proxy_streams?: boolean;
}

/**
 * Platform specific configuration
 * This will get passed onto the adapter (if applicable)
 */
export interface Platforms {
	netlify?: Netlify;
	node?: Node;
	vercel?: Vercel;
}

export interface Netlify {
	edge?: boolean;
	split?: boolean;
}

export interface Node {
	envPrefix?: string;
	out?: string;
	precompress?: boolean;
}

export interface Vercel {
	edge?: boolean;
	external?: string[];
	split?: boolean;
}

export type Adapter = "node" | "vercel" | "netlify" | "cloudflare-workers";
